//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelekomNevaSvyazWpfApp.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscriber
    {
        public string Number { get; set; }
        public string FullName { get; set; }
        public int GenderId { get; set; }
        public System.DateTime BirthDay { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public string RegistrationAddress { get; set; }
        public string LivingAddress { get; set; }
        public string PassportSeriesAndNumber { get; set; }
        public string SubdivisionCode { get; set; }
        public string WhoGavePassport { get; set; }
        public System.DateTime PassportGaveDate { get; set; }
        public string ContractNumber { get; set; }
        public System.DateTime ContractDate { get; set; }
        public int ContractTypeId { get; set; }
        public string ContractRejectReason { get; set; }
        public string PersonalAccount { get; set; }
        public Nullable<System.DateTime> ContractRejectDate { get; set; }
    
        public virtual ContractType ContractType { get; set; }
        public virtual Gender Gender { get; set; }
    }
}
